### ISSUE TITLE
Přidávání do jednoho CSV souboru

### ISSUE THREAD

**Issue by mjirik** [mjirik/lisa#117]
Jde o to, aby pak šlo data snáze hromadně vyhodnocovat.

Pokaždé, když se klikne na "Save report to CSV" ukládat kromě normálního reportu ještě přidat jeden řádek do dalšího souboru. Ten by měl vypadat nějak takhle:

http://nbviewer.ipython.org/urls/dl.dropbox.com/s/ot5k7gb7djkbln5/2015-konz-JK.ipynb?dl=0

**Comment by kunesj** [comment]
Hotovo, ukládá se do souboru statsRecords.csv. Uložení se spustí kliknutím na jakékoliv tlačítko na uložení výsledků, přičemž se provede maximálně jednou za chod programu (aby nebyli duplikátní záznamy).

**Comment by mjirik** [comment]
Chytré, to mě nenapadlo. Bezva.
