### ISSUE TITLE
nefunguje support structure segmentation

### ISSUE THREAD

**Issue by mjirik** [mjirik/lisa#120]
39
plice separované
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/home/mjirik/projects/lisa/lisa/lisaWindow.pyc in autoSeg(self)
    578             return
    579 
--> 580         self.oseg.run_sss()
    581         self.statusBar().showMessage('Automatic segmentation finished')
    582 

/home/mjirik/projects/lisa/lisa/organ_segmentation.py in run_sss(self)
    292         # sseg.bone_segmentation()
    293         sseg.lungs_segmentation()
--> 294         sseg.heart_segmentation()
    295         self.segmentation = sseg.segmentation
    296 

/home/mjirik/projects/lisa/lisa/support_structure_segmentation.pyc in heart_segmentation(self, heart_treshold)
    150         s = np.array([x , y]).T
    151         h = np.array(z)
--> 152         model = mpf.multipolyfit(s, h, self.rad_diaphragm, model_out = True)
    153         ran = self.segmentation.shape
    154         x = np.arange( ran[1] )

/home/mjirik/.local/lib/python2.7/site-packages/multipolyfit/core.pyc in multipolyfit(xs, y, deg, full, model_out, powers_out)
     64     A = hstack(asarray([as_tall((xs**p).prod(1)) for p in powers]))
     65 
---> 66     beta = linalg.lstsq(A, y)[0]
     67 
     68     if model_out:

/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.pyc in lstsq(a, b, rcond)
   1835     a, bstar = _to_native_byte_order(a, bstar)
   1836     s = zeros((min(m, n),), real_t)
-> 1837     nlvl = max( 0, int( math.log( float(min(m, n))/2. ) ) + 1 )
   1838     iwork = zeros((3*min(m, n)*nlvl+11*min(m, n),), fortran_int)
   1839     if isComplexType(t):

ValueError: math domain error

**Comment by Trineon** [comment]
Opraveno ale jenom tak dočasně je tam někdě problem s těma slabama
nefungujou jak by měli kouknu na to. Ona stejně ta heart_segmentation zatim
ukazuje jenom to co je na bránicí a má určitej prah


2015-04-07 10:51 GMT+02:00 Miroslav Jiřík <notifications@github.com>:

**Comment by mjirik** [comment]
Nevadí, chci jim ukázat hlavně ten koncept. Pro tyhle účely to funguje uspokojivě.
